backend:
  name: github
  repo: Tasemu/dion-tabrett

media_folder: static/assets
public_folder: assets

collections:
  - name: home
    label: Home Page
    folder: home
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
